version: "3.3"
services:
  app:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    links:
      - db
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    # restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: my_service
      MYSQL_USER: dev
      MYSQL_PASSWORD: secret
